// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARQsBhMRq5_jSTaHtgvxIVRqbozdt_MUI',
    appId: '1:908642810097:web:3716ca81b1aa0faf9ad150',
    messagingSenderId: '908642810097',
    projectId: 'smart-ho-b25db',
    authDomain: 'smart-ho-b25db.firebaseapp.com',
    storageBucket: 'smart-ho-b25db.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLFroarvk36h6mf6SW94Of2f3pdTdvEoA',
    appId: '1:908642810097:android:f8f91959558c36b09ad150',
    messagingSenderId: '908642810097',
    projectId: 'smart-ho-b25db',
    storageBucket: 'smart-ho-b25db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY1iv9QwGD9SU-8Q6OU-JzlNwGnoKgct0',
    appId: '1:908642810097:ios:a1dba7e664cbff399ad150',
    messagingSenderId: '908642810097',
    projectId: 'smart-ho-b25db',
    storageBucket: 'smart-ho-b25db.appspot.com',
    iosBundleId: 'com.example.smartHome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDY1iv9QwGD9SU-8Q6OU-JzlNwGnoKgct0',
    appId: '1:908642810097:ios:a1dba7e664cbff399ad150',
    messagingSenderId: '908642810097',
    projectId: 'smart-ho-b25db',
    storageBucket: 'smart-ho-b25db.appspot.com',
    iosBundleId: 'com.example.smartHome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARQsBhMRq5_jSTaHtgvxIVRqbozdt_MUI',
    appId: '1:908642810097:web:241cc93cfa3574ae9ad150',
    messagingSenderId: '908642810097',
    projectId: 'smart-ho-b25db',
    authDomain: 'smart-ho-b25db.firebaseapp.com',
    storageBucket: 'smart-ho-b25db.appspot.com',
  );

}